### ISSUE TITLE
v1.0.0 Release Plan

### ISSUE THREAD

**Issue by shibayan** [shibayan/AppServiceProxy.SiteExtension#1]
- [x] Basic `proxies.json` feature support
  - [x] Match condition
  - [x] Backend uri
  - [x] Request overrides
  - [x] Response overrides
  - [x] Expand app settings value
  - [x] Catch all #4 
- [x] Reload on `proxies.json` changed #2 
- [x] Optimize `web.config` for reverse proxy #5 
- [x] Workflow
  - [x] Build #3 
  - [x] Release #6
- [x] Test
  - [x] Unit test
  - [x] Azure
- [x] Renaming for release #7 
- [x] Documentation #9
